// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrEf519E2d7XBKieDRzB4y3yJDlmfREE',
    appId: '1:429752960042:web:1b2b63f2b14602800e6f53',
    messagingSenderId: '429752960042',
    projectId: 'chat-app-29d11',
    authDomain: 'chat-app-29d11.firebaseapp.com',
    storageBucket: 'chat-app-29d11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSI6NYiXt9pZzUq9wuaEXh9UT7MgB35vI',
    appId: '1:429752960042:android:e919811a8f8d6b0d0e6f53',
    messagingSenderId: '429752960042',
    projectId: 'chat-app-29d11',
    storageBucket: 'chat-app-29d11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9nDp8h3Yj4Wl93vyc2L_8M8ML_vi0lQ',
    appId: '1:429752960042:ios:1510ffeca274049e0e6f53',
    messagingSenderId: '429752960042',
    projectId: 'chat-app-29d11',
    storageBucket: 'chat-app-29d11.appspot.com',
    iosClientId: '429752960042-9ljbrh302dgsd5codvlhnuhfm8apu73d.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb9nDp8h3Yj4Wl93vyc2L_8M8ML_vi0lQ',
    appId: '1:429752960042:ios:1510ffeca274049e0e6f53',
    messagingSenderId: '429752960042',
    projectId: 'chat-app-29d11',
    storageBucket: 'chat-app-29d11.appspot.com',
    iosClientId: '429752960042-9ljbrh302dgsd5codvlhnuhfm8apu73d.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoChatApp',
  );
}
